#!/usr/bin/env bash

set -uo pipefail

SCRIPTPATH=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
export SCRIPTPATH

# down the last running theme
if [ -h "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s "${SCRIPTPATH}/down" /tmp/leftwm-theme-down

leftwm command "LoadTheme ${SCRIPTPATH}/theme.toml"

#set background
# if [ -x "$(command -v feh)" ]; then
#   feh --bg-scale "$SCRIPTPATH/background.jpg"
# fi

hostname=$(hostname)

WORKSPACE=0
for MONITOR in $(polybar -m | sed s/:.*//); do
	barname="$hostname$WORKSPACE"
	export WORKSPACE
	export MONITOR

	polybar -c "$SCRIPTPATH/polybar.ini" "$barname" &
	((WORKSPACE = WORKSPACE + 1))
done
