cabal-version: 2.4
name:          taffybar-kid
version:       0.1.0.0
category:      System
build-type:    Simple


executable taffybar-kid
  main-is:          taffybar.hs
  build-depends:
      base
    , containers
    , directory
    , filepath
    , gi-gtk
    , gtk-sni-tray
    , gtk-strut
    , time
    , taffybar

  hs-source-dirs:   .
  default-language: Haskell2010
